### ISSUE TITLE
Support for 5.49.7

### ISSUE THREAD

**Issue by leppeK** [ToonSoftwareCollective/resourcefiles#4]
No support for 5.49.7 for now, can you provide the neccesary resource files?

**Comment by leppeK** [comment]
@IgorYbema I see you provided an update but not the resourcefiles, could you upload these?

**Comment by IgorYbema** [comment]
@leppeK sorry, forgot to add the files to the commit :) there are there now

**Comment by leppeK** [comment]
can confirm it is working now
